version: "3.9"

services:
  fast_api:
    container_name: fast_api_api
    build:
      context: ./fast_api
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2000M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "8081:8081"
  flask:
    container_name: flask_api
    build:
      context: ./flask
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2000M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "8082:8082"

  fiber:
    container_name: fiber_api
    build:
      context: ./fiber
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2000M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "8083:8083"

  gin:
    container_name: gin_api
    build:
      context: ./gin
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2000M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "8084:8084"

  akka:
    container_name: akka
    build:
      context: ./akka
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2000M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "8085:8085"

  comparison:
    container_name: comparison_script
    build:
      context: ./comparison
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 500M
        reservations:
          cpus: '2.0'
          memory: 500M
    volumes:
      - ./comparison/results:/app/results
    depends_on:
      - fiber
      - flask
      - fast_api
      - gin
      - akka