version: "3.9"

services:
  fast_api:
    build:
      context: ./fast_api
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
        reservations:
          cpus: '0.01'
          memory: 100M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "8081:8080"
  flask:
    build:
      context: ./flask
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
        reservations:
          cpus: '0.01'
          memory: 100M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "8082:8081"

  fiber:
    build:
      context: ./fiber
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
        reservations:
          cpus: '0.01'
          memory: 100M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "8083:8082"