version: "3.9"

services:
  fast-api:
    container_name: fast-api
    build:
      context: ./fast_api
      dockerfile: ./Dockerfile
    env_file:
      .env
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 3000M
      restart_policy:
        condition: on-failure
        max_attempts: 2
    ports:
      - "8081:8081"
  flask:
    container_name: flask
    build:
      context: ./flask
      dockerfile: ./Dockerfile
    env_file:
        .env
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 3000M
      restart_policy:
        condition: on-failure
        max_attempts: 2
    ports:
    - "8082:8082"

  fiber:
    container_name: fiber
    build:
      context: ./fiber
      dockerfile: ./Dockerfile
    env_file:
      .env
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 3000M
      restart_policy:
        condition: on-failure
        max_attempts: 2
    ports:
    - "8083:8083"

  gin:
    container_name: gin
    build:
      context: ./gin
      dockerfile: ./Dockerfile
    env_file:
      .env
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 3000M
      restart_policy:
        condition: on-failure
        max_attempts: 2
    ports:
    - "8084:8084"

  akka:
    container_name: akka
    build:
      context: ./akka
      dockerfile: ./Dockerfile
    env_file:
      .env
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 3000M
      restart_policy:
        condition: on-failure
        max_attempts: 2
    ports:
    - "8085:8085"
#
#  dotnet:
#    container_name: dotnet
#    build:
#      context: ./dotnet
#      dockerfile: ./Dockerfile
#    env_file:
#      .env
#    deploy:
##      resources:
##        limits:
##          cpus: '2.0'
##          memory: 2000M
#      restart_policy:
#        condition: on-failure
#        max_attempts: 2
#    ports:
#      - "8086:8086"

  comparison:
    container_name: comparison_script
    build:
      context: ./comparison
      dockerfile: ./Dockerfile
    env_file:
      .env
#    deploy:
#      resources:
#        limits:
#          cpus: '2.0'
#          memory: 2000M
    volumes:
      - ./comparison/results:/app/results
    depends_on:
       - fiber
       - flask
       - fast-api
       - gin
       - akka
#       - dotnet